version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: marus
      POSTGRES_PASSWORD: marus
    ports:
      - "5432:5432"

  app:
    build: .
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards
      SPRING_DATASOURCE_USERNAME: marus
      SPRING_DATASOURCE_PASSWORD: marus
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
